name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build the application
      run: ./gradlew build

    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build . \
          --file Dockerfile \
          --tag your-image-name:$(date +%s) \
          --build-arg JAR_FILE=build/libs/your-application.jar

    - name: Push the Docker image to Docker Hub
      run: |
        echo $DOCKER_USERNAME | docker login -u $DOCKER_PASSWORD --password-stdin
        docker push invoice_builder-0.0.1:$(date +%s)
